### ISSUE TITLE
Can't scroll on liquipedia.net

### ISSUE THREAD

**Issue by flaccida** [Christoph142/modern-scroll#195]
e.g. https://liquipedia.net/dota2/Main_Page

**Comment by Christoph142** [comment]
Thanks for mentioning this page. I can reproduce the issue and I'm gonna have a look if it can be fixed. 🙂👍

**Comment by Christoph142** [comment]
Wow. That page is a mess. 🙈
Do you know the website owner?
I have an easy fix, but I'd rather have them alter it globally (since it looks like a general error that browsers will forcefully ignore).

**Comment by FO-nTTaX** [comment]
@flaccida I changed something on the Liquipedia page. I cleared the cache on the page you linked, maybe you could tell me if this fixes the issues you had?

Due to our cache system this fix might take up to a week to fully get to all pages on our wiki, but if you could verify it for the linked page that would be great.

**Comment by Christoph142** [comment]
It's working fine now. Thanks for looking into it @FO-nTTaX ! 💯
