### ISSUE TITLE
Not sure who's at fault.

### ISSUE THREAD

**Issue by BLooRT** [Christoph142/modern-scroll#218]
I'll try to be concise.. haha.  When i open an epochtimes.com news article (paywalled) they have an advertisment at the top of the page.  with modern scroll enabled, the advertisement gains a scroll bar and you can then hover and scroll down inside the ad's box down into a lot of extra and blank verticle space.  So could be a shortcoming in their code as they are just updating the site recently. PHP is a fickle mistress.  but in case it's your bug, i figure i would raise the alarm.

The funny bit is, i was zoomed 125%, so the modified ad box took up nearly the whole screen, the scroll bar fell off the visible screen space off to the right, and i'm scrolling up and down, not knowing i'm inside the ad box thinking, well... that page is fubar, what are those guys doing?  nothing but white space. lol  fool me 6 times but not 7 apparently. heh heh

and dude..... modern scroll is a dream come true for me. can't state that or thank you enough. amazing

**Comment by Christoph142** [comment]
Hi @BLooRT, thanks for the kind words. I'm glad you like it! 🙂 Is it just one specific ad or all of them? Maybe you could save an affected page as mhtml file and send it to me so I can have a look at what's wrong if there's no way to get to the issue behind the paywall for me without an account?

**Comment by Christoph142** [comment]
I just tried to get a glimpse as much as I could. I didn't see the issue itself, but I think I know what's happening. I stumbled across this on another page recently. Neither modern scroll, nor the page is to blame, but Google is.
Google ads recently seems to have started using iframes with scrolling=no specified on them. This used to be valid syntax a few years back, but it simply does **not** exist in HTML5. It's invalid.
The good thing (in terms of privacy) is that iframes nowadays are completely separated from the main page and there is no interconnection. However, this is bad news for modern scroll, because there is imply no way for the bars in the ads to know that the page it is embedded in specifies a certain attribute (scrolling=no). It's impossible to detect. So I'm afraid the only way to make this work is for Google to fix their invalid HTML code. 😕

**Comment by BLooRT** [comment]
sounds like you nailed it.  it was the first time i had seen that happen.
I gave epoch times a quick note about it, and it seems they have already
taken the ad frame out from their articles.  they are an amazing crew,
doing great work.  youtube started hassling them, so screw it.. they made
their own media server so now they can't be censored.  and it works pretty
darn good too.  But with iframe deal, it's nice to see the big boys are at
fault, and not modern scroll or the epoch times. haha

not sure why, but i'm gonna share a funny story from before the internet.
Bob had just scored a raft of handy new dos command tools, and we were
trying them out.  being restricted to 8.3 names, most names were pretty
obvious as to what they did... but some were guesswork, so you had to try
them out with specifying a test file.  so like, C: xcopy testfile.txt etc.
then bob looked at the next tool, called delbut.exe.  shrugged his
shoulders and typed c: delbut testfile.txt    anticlimactic cause not much
happened on the screen, but a dir command showed that he had successfully
DELeted everything BUT testfile.txt  heh heh.  that turned into a running
gag for years after.  I think cokegift.exe was the next big thing.  it
ejected your cdrom to provide you with a drink holder.

**Comment by BLooRT** [comment]
and boom, the ad is back on epoch times and they fixed it.  modern scroll
now works flawlessly on their new pages.

**Comment by Christoph142** [comment]
Perfect. Thanks for the updates. I'm closing this then.
